apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: ocm-with-helm
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/backend-application-helm
  version:
    semver: v1.0.0
  repository:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds