apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: ocm-with-helm-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: ocm-with-helm
    namespace: ocm-system
  resource:
    name: deployment
  snapshotTemplate:
    name: ocm-with-helm-snap-deployment
